### ISSUE TITLE
"Neomake: [1.2:1:1] Error during output processing for pylint: Vim(lwindow):Zero count: lwindow 0."

### ISSUE THREAD

**Issue by sheriferson** [neomake/neomake#1705]
I tried searching past issues and elsewhere online for other instances of this problem but didn't find any other cases.

I use pylint checking via Neomake in Neovim. I have Neomake set up to run automatically. Here are all the relevant lines from my `init.vim`:

```
" Neomake
let g:neomake_open_list = 2
let g:neomake_python_python_exe = 'python3'

let g:neomake_python_pylint_maker = {
    \ 'args': [
    \ '-d', 'C0103,C1801,C0325',
    \ '-f', 'text',
    \ '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"',
    \ '-r', 'n'
    \ ],
    \ 'errorformat':
    \ '%A%f:%l:%c:%t: %m,' .
    \ '%A%f:%l: %m,' .
    \ '%A%f:(%l): %m,' .
    \ '%-Z%p^%.%#,' .
    \ '%-G%.%#',
    \ }

autocmd! BufWritePost,BufReadPost * Neomake
```

When opening a python file that produces no warnings or errors from pylint, I get an error in nvim's status bar that reads `Neomake: [1.2:1:1] Error during output processing for pylint: Vim(lwindow):Zero count: lwindow 0.` Neomake then no longer runs any checks whenever I save the file. This issue does not happen if I start editing a file that does produce warnings or errors from pylint - in that case, Neomake behaves as expected and opens a list window in the bottom, and automatically updates the list of warnings as I fix them and update the file. The error mentioned above does return when I fix the final warning, and Neomake stops checking the file on save.

### Expected behavior

The behavior I expect and got until recently is that there would be no window in the bottom when there are no issues with the file I'm editing, and once I save changes that cause pylint to issue some warnings, the window would appear and list the warnings. I expect Neomake to run the checks automatically every time I save the file. I think this behavior changed/broke with a recent update.

### Steps to reproduce

Open a python file that does not produce any pylint errors or warnings. The output below is from editing a file: `~/Desktop/test.py` with contents:

```python
"""
test
"""
print('Hello world')
```

### Output from (verbose) NeomakeInfo

<details>

#### Neomake debug information
Async support: 1
Current filetype: python
Windows: 0
[shell, shellcmdflag, shellslash]: ['bash', '-c', 0]

##### Enabled makers
For the current filetype ("python", used with :Neomake):
 - python
   - append_file: 1
   - args: ['/Users/shersol/.config/nvim/bundle/neomake/autoload/neomake/makers/ft/python/compile.py']
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%c: %m'
   - exe: 'python3'
   - output_stream: 'stdout'
   - serialize: 1
   - serialize_abort_on_error: 1
   - short_name: 'py'
 - frosted
   - append_file: 1
   - args: ['-vb']
   - auto_enabled: 1
   - errorformat: '%f:%l:%c:%m,%E%f:%l: %m,%-Z%p^,%-G%.%#'
   - exe: 'frosted'
   - WARNINGS:
     - maker's exe (frosted) is not executable.
 - pyflakes
   - append_file: 1
   - args: []
   - auto_enabled: 1
   - errorformat: '%E%f:%l: could not compile,%-Z%p^,%E%f:%l:%c: %m,%E%f:%l: %m,%-G%.%#'
   - exe: 'pyflakes'
   - WARNINGS:
     - maker's exe (pyflakes) is not executable.
 - pycodestyle
   - append_file: 1
   - args: []
   - auto_enabled: 1
   - errorformat: '%f:%l:%c: %m'
   - exe: 'pep8'
   - postprocess: function('neomake#makers#ft#python#Pep8EntryProcess')
   - WARNINGS:
     - maker's exe (pep8) is not executable.
 - pydocstyle
   - append_file: 1
   - args: []
   - auto_enabled: 1
   - errorformat: '%W%f:%l %.%#:,%+C        %m'
   - exe: 'pep257'
   - postprocess: function('neomake#utils#CompressWhitespace')
   - WARNINGS:
     - maker's exe (pep257) is not executable.
 - pylint
   - args: ['-d', 'C0103,C1801,C0325', '-f', 'text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"', '-r', 'n']
   - auto_enabled: 1
   - errorformat: '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#'
   - exe: 'pylint'
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_open_list = 2
g:neomake_place_signs = 1
g:neomake_python_pylint_maker = {'errorformat': '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#', 'args': ['-d', 'C0103,C1801,C0325', '-f', 'te
xt', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"', '-r', 'n']}
g:neomake_python_python_exe = 'python3'
g:neomake_verbose = 3

  makeprg=make
```

#### :version
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDI
SABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERA
TED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/u
sr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neo
vim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

#### :messages
```
"test.py" 1L, 21C
Neomake [     ]: [1.-:1:1] Calling Make with options {'ft': 'python', 'file_mode': 1}.
Neomake [+0.01]: [1.-:1:1] Exe (frosted) of auto-configured maker frosted is not executable, skipping.
Neomake [     ]: [1.-:1:1] Exe (pyflakes) of auto-configured maker pyflakes is not executable, skipping.
Neomake [     ]: [1.-:1:1] Exe (pep8) of auto-configured maker pycodestyle is not executable, skipping.
Neomake [     ]: [1.-:1:1] Exe (pep257) of auto-configured maker pydocstyle is not executable, skipping.
Neomake [     ]: [1.-:1:1] Running makers: python (auto), pylint (auto).
Neomake [     ]: [1.1:1:1] Setting neomake_automake_tick.
Neomake [     ]: Skipping User autocmd NeomakeJobInit: no hooks.
Neomake [     ]: [1.1:1:1] Starting async job: ['python3', '/Users/shersol/.config/nvim/bundle/neomake/autoload/neomake/makers/ft/python/compile.py', '/Users/s
hersol/Desktop/test.py'].
Neomake [     ]: [1.1:1:1] cwd: /Users/shersol/Desktop.
Neomake [     ]: [1.1:1:1] Calling User autocmd NeomakeJobStarted with context: {'jobinfo': '…'}.
Neomake [+0.45]: [1.1:1:1] exit: python: 0.
Neomake [     ]: [1.1:1:1] python: completed with exit code 0.
Neomake [     ]: [1.1:1:1] Cleaning jobinfo.
Neomake [     ]: [1.1:1:1] Calling User autocmd NeomakeJobFinished with context: {'jobinfo': '…'}.
Neomake [     ]: Skipping User autocmd NeomakeJobInit: no hooks.
Neomake [     ]: [1.2:1:1] Starting async job: ['pylint', '-d', 'C0103,C1801,C0325', '-f', 'text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg
}"', '-r', 'n', '/Users/shersol/Desktop/test.py'].
Neomake [     ]: [1.2:1:1] cwd: /Users/shersol/Desktop.
Neomake [     ]: [1.2:1:1] Calling User autocmd NeomakeJobStarted with context: {'jobinfo': '…'}.
Neomake [+0.52]: [1.2:1:1] stderr: pylint: ['No config file found, using default configuration', ''].
Neomake [+0.04]: [1.2:1:1] stdout: pylint: ['************* Module test', 'test.py:1:0:C: [missing-docstring] Missing module docstring', '', '------------------
-----------------', 'Your code has been rated at 0.00/10', '', ''].
Neomake [+0.04]: [1.2:1:1] exit: pylint: 16.
Neomake [     ]: [1.2:1:1] pylint: processing 6 lines of output.
Neomake [     ]: [1.-:-:1] Creating location list.
Neomake [     ]: [1.2:1:1] Processing 1 entries.
Neomake [     ]: [1.-:1:1] File-level errors cleaned.
Neomake [     ]: [-.-:1:1] Placing sign: sign place 5000 line=1 name=neomake_file_err buffer=1.
Neomake [     ]: Skipping User autocmd NeomakeCountsChanged: no hooks.
Neomake [     ]: [1.2:1:1] Handling location list: executing lwindow.
Neomake [+0.03]: [-.-:-:2] Ignoring Make through autocommand due to s:ignore_automake_events=1.
Neomake [+0.01]: [1.2:1:1] pylint: processing 1 lines of output.
Neomake [     ]: [1.2:1:1] Processing 0 entries.
Neomake [     ]: [1.2:1:1] Handling location list: executing lwindow.
Neomake [     ]: [1.2:1:1] pylint: completed with exit code 16.
Neomake [     ]: [1.2:1:1] Cleaning jobinfo.
Neomake [     ]: [1.2:1:1] Calling User autocmd NeomakeJobFinished with context: {'jobinfo': '…'}.
Neomake [     ]: WideMessage: echo pylint: [missing-docstring] Missing module docstring (C).
Neomake [     ]: Skipping User autocmd NeomakeFinished: no hooks.
Neomake [     ]: [1.-:1:1] Cleaning make info.
"test.py" 4L, 34C written
Neomake [+5.83]: [2.-:1:1] Calling Make with options {'ft': 'python', 'file_mode': 1}.
Neomake [+0.01]: [2.-:1:1] Exe (frosted) of auto-configured maker frosted is not executable, skipping.
Neomake [     ]: [2.-:1:1] Exe (pyflakes) of auto-configured maker pyflakes is not executable, skipping.
Neomake [     ]: [2.-:1:1] Exe (pep8) of auto-configured maker pycodestyle is not executable, skipping.
Neomake [     ]: [2.-:1:1] Exe (pep257) of auto-configured maker pydocstyle is not executable, skipping.
Neomake [     ]: [2.-:1:1] Running makers: python (auto), pylint (auto).
Neomake [     ]: Skipping User autocmd NeomakeCountsChanged: no hooks.
Neomake [     ]: [2.3:1:1] Setting neomake_automake_tick.
Neomake [     ]: Skipping User autocmd NeomakeJobInit: no hooks.
Neomake [     ]: [2.3:1:1] Starting async job: ['python3', '/Users/shersol/.config/nvim/bundle/neomake/autoload/neomake/makers/ft/python/compile.py', '/Users/s
hersol/Desktop/test.py'].
Neomake [     ]: [2.3:1:1] cwd: /Users/shersol/Desktop.
Neomake [     ]: [2.3:1:1] Calling User autocmd NeomakeJobStarted with context: {'jobinfo': '…'}.
Neomake [+0.08]: [2.3:1:1] exit: python: 0.
Neomake [     ]: [2.3:1:1] python: completed with exit code 0.
Neomake [     ]: [2.3:1:1] Cleaning jobinfo.
Neomake [     ]: [2.3:1:1] Calling User autocmd NeomakeJobFinished with context: {'jobinfo': '…'}.
Neomake [     ]: Skipping User autocmd NeomakeJobInit: no hooks.
Neomake [     ]: [2.4:1:1] Starting async job: ['pylint', '-d', 'C0103,C1801,C0325', '-f', 'text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg
}"', '-r', 'n', '/Users/shersol/Desktop/test.py'].
Neomake [     ]: [2.4:1:1] cwd: /Users/shersol/Desktop.
Neomake [     ]: [2.4:1:1] Calling User autocmd NeomakeJobStarted with context: {'jobinfo': '…'}.
Neomake [+0.46]: [2.4:1:1] stderr: pylint: ['No config file found, using default configuration', ''].
Neomake [+0.03]: [2.4:1:1] stdout: pylint: ['', '--------------------------------------------------------------------', 'Your code has been rated at 10.00/10 (
previous run: 0.00/10, +10.00)', '', ''].
Neomake [+0.04]: [2.4:1:1] exit: pylint: 0.
Neomake [     ]: [2.4:1:1] pylint: processing 4 lines of output.
Neomake [     ]: [2.-:-:1] Creating location list.
Neomake [+0.01]: [3.-:2:2] Calling Make with options {'ft': 'qf', 'file_mode': 1}.
Neomake [     ]: [3.-:2:2] Nothing to make: no enabled file mode makers (filetype=qf).
Neomake [     ]: [3.-:2:2] Cleaning make info.
Neomake [+0.02]: [4.-:2:2] Calling Make with options {'ft': 'qf', 'file_mode': 1}.
Neomake [     ]: [4.-:2:2] Nothing to make: no enabled file mode makers (filetype=qf).
Neomake [     ]: [4.-:2:2] Cleaning make info.
Neomake [     ]: [2.4:1:1] Processing 0 entries.
Neomake [     ]: [2.-:1:1] File-level errors cleaned.
Neomake [     ]: [2.4:1:1] Handling location list: executing lwindow.
Neomake error in: function <SNR>94_nvim_exit_handler[6]..<SNR>94_exit_handler[27]..<SNR>94_RegisterJobOutput[16]..<SNR>94_ProcessJobOutput[6]..<SNR>94_pcall[3]
..<SNR>94_ProcessJobOutput[80]..<SNR>94_AddExprCallback[136]..<SNR>94_ProcessEntries[6]..<SNR>94_pcall[3]..<SNR>94_ProcessEntries[154]..<SNR>94_HandleLoclistQf
listDisplay, line 20
Neomake [     ]: [2.4:1:1] Error during output processing for pylint: Vim(lwindow):Zero count: lwindow 0.
Neomake [     ]: [2.4:1:1] (in function <SNR>94_nvim_exit_handler[6]..<SNR>94_exit_handler[27]..<SNR>94_RegisterJobOutput[16]..<SNR>94_ProcessJobOutput[6]..<SN
R>94_pcall[3]..<SNR>94_ProcessJobOutput[80]..<SNR>94_AddExprCallback[136]..<SNR>94_ProcessEntries[6]..<SNR>94_pcall[3]..<SNR>94_ProcessEntries[154]..<SNR>94_Ha
ndleLoclistQflistDisplay, line 20)
Neomake [     ]: [2.4:1:1] pylint: processing 1 lines of output.
Neomake [+0.01]: [-.-:-:2] Ignoring Make through autocommand due to s:ignore_automake_events=1.
Neomake [     ]: [2.4:1:1] Processing 0 entries.
Neomake [     ]: [2.4:1:1] Handling location list: executing lwindow.
Neomake error in: function <SNR>94_nvim_exit_handler[6]..<SNR>94_exit_handler[27]..<SNR>94_RegisterJobOutput[16]..<SNR>94_ProcessJobOutput[6]..<SNR>94_pcall[3]
..<SNR>94_ProcessJobOutput[80]..<SNR>94_AddExprCallback[136]..<SNR>94_ProcessEntries[6]..<SNR>94_pcall[3]..<SNR>94_ProcessEntries[154]..<SNR>94_HandleLoclistQf
listDisplay, line 20
Neomake [     ]: [2.4:1:1] Error during output processing for pylint: Vim(lwindow):Zero count: lwindow 0.
Neomake [     ]: [2.4:1:1] (in function <SNR>94_nvim_exit_handler[6]..<SNR>94_exit_handler[27]..<SNR>94_RegisterJobOutput[16]..<SNR>94_ProcessJobOutput[6]..<SN
R>94_pcall[3]..<SNR>94_ProcessJobOutput[80]..<SNR>94_AddExprCallback[136]..<SNR>94_ProcessEntries[6]..<SNR>94_pcall[3]..<SNR>94_ProcessEntries[154]..<SNR>94_Ha
ndleLoclistQflistDisplay, line 20)
Neomake [     ]: [2.4:1:1] pylint: completed with exit code 0.
Neomake [     ]: [2.4:1:1] Cleaning jobinfo.
Neomake [     ]: [2.4:1:1] Calling User autocmd NeomakeJobFinished with context: {'jobinfo': '…'}.
Neomake [     ]: Cleaning old signs in buffer 1: {5000: neomake_file_err}.
Neomake [     ]: Unplacing sign: sign unplace 5000 buffer=1.
Neomake [     ]: [-.-:-:1] Handling location list: executing lclose.
Neomake [     ]: Skipping User autocmd NeomakeFinished: no hooks.
Neomake [     ]: [2.-:1:1] Cleaning make info.
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDI
SABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERA
TED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/u
sr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neo
vim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
2 fewer lines; before #3  67 seconds ago
1 line less; before #2  70 seconds ago
1 more line; after #2  71 seconds ago
2 more lines; after #3  70 seconds ago
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDI
SABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERA
TED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/u
sr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neo
vim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
```
</details>

**Comment by sheriferson** [comment]
I tried replacing `autocmd! BufWritePost,BufReadPost * Neomake` with `call neomake#configure#automake('w')` as mentioned in the README, and at first I thought the problem was fixed because I was no longer getting an error on opening a file, and even got warnings when I added an intentional bad import. But after fixing the bad line (which resolved all warnings/error), I got the error again, and Neomake is no longer automatically checking the file.

**Comment by blueyed** [comment]
Sounds related to https://github.com/neomake/neomake/commit/06524356b9195c413ce56b97565d046933c80ccc (rather new).

**Comment by blueyed** [comment]
I think https://github.com/neomake/neomake/pull/1708 should help here.
Will add a test / improve the tests in this regard later.

**Comment by sheriferson** [comment]
I just updated to the latest version and it seems fixed : ) Thanks for looking at it so quickly.

**Comment by blueyed** [comment]
Thanks for reporting it!

Digging into this showed a lot of issues with the tests: still not sure if there is some existing test covering it, but errors (converted to Vim messages like this) were not really handled well.

**Comment by blueyed** [comment]
btw: you have a lot of makers running (related to https://github.com/neomake/neomake/issues/1702).
You might want to configure only specific ones, e.g. `let g:neomake_python_makers = ['python', 'pylint']`.

**Comment by sheriferson** [comment]
Thanks for the tip, I appreciate it! I think it's time I read all of `:help Neomake` which I've been putting off for a while.
